config/routes.rb
GameWatcha::Application.routes.draw do
  resources :game_infos

  post "api/signin"
  post "api/signup"
  post "api/game_info"
  post "api/make_comment"
  post "api/set_rating"
  post "api/wish"
  get "page/index"
  get "picbox" => "page#my_wish"
  post "/api/delete_comment"
  root "page#index"
  post "/api/set_user_platform"
  get "main" => "page#main"
  get "detail" => "page#detail"
  get "select" => "page#select"
  devise_for :users
  resources :games

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_attached_file :image, :styles => { :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_one :game_info
  has_many :comments
  has_many :ratings
  has_many :wishes
  has_many :game_movies
  has_many :platform_games
  has_many :platforms, :through => :platform_games
  has_one :game_stat

  def genre_names
    genres = self.genre_ids.split("/")
    names = Array.new
    genres.each do |genre|
      names.push(Genre.find(genre).name)
    end

    names.join(", ")
  end

  def platform_names
    names = Array.new
    self.platforms.each do |platform|
      names.push(Platform.find(platform).name)
    end

    names.join(", ")
  end

  def get_comment_data
    comments = self.comments
    ret = Array.new
    comments.each do |comment|
      c = comment.attributes
      c["email"] = comment.user.email
      c["score"] = comment.rate
      ret.push(c)
    end
    ret
  end

  def set_rate score, user_id
    rating = Rating.where(game_id: self.id, user_id: user_id).first
    if rating.nil?
      rating = Rating.new
      rating.game_id = self.id
      rating.user_id = user_id
    end
    rating.score = score
    rating.save
  end

  def rate user_id
    rating = Rating.where(game_id: self.id, user_id: user_id).first
    score = 0
    unless rating.nil?
      score = rating.score
    end
    score
  end

  def wish? user_id
    wish = Wish.where(game_id:self.id, user_id: user_id).first
    !wish.nil?
  end

  def self.get_platform_game user
    platform_ids = user.platform_ids
    platform_games = PlatformGame.where(:platform_id => platform_ids)

    games = Array.new
    platform_games.each do |p_g|
      games.push(p_g.game)
    end
    games.uniq
  end
  def self.data_from_seed seed
    game = Game.new
    #장르
    game.genre_ids = Genre.set_genre_from_seed(seed[:genre])
    game.image = File.open("#{Rails.root}/seed/image#{seed[:small_image]}")
    #게임 이름
    game.name = seed[:name]
    game.save
    #제작사
    game_info = GameInfo.new
    game_info.game_id = game.id

    game_info.maker = seed[:maker]

    game_info.image = File.open("#{Rails.root}/seed/image#{seed[:big_image]}")
    #유통사
    game_info.distribute = seed[:distribute]
    #출시날짜
    game_info.date = seed[:date]
    #이용등급
    game_info.user_class = seed[:user_class]
    #소개
    game_info.content = seed[:content]
    game_info.save
    #소개영상링크
    GameMovie.create(game_id: game.id, movie_url: seed[:movie])
    PlatformGame.set_platform_from_seed(seed[:platform], game.id)
    if game.game_stat.nil?
      GameStat.create(game_id:game.id)
    end
    game_stat = GameStat.where(game_id: game.id).first
    game_stat.stat0 = seed[:stat0]
    game_stat.stat1 = seed[:stat1]
    game_stat.stat2 = seed[:stat2]
    game_stat.stat3 = seed[:stat3]
    game_stat.stat4 = seed[:stat4]
    game_stat.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :wishes
  has_many :platform_users
  has_many :platforms, :through => :platform_users
  has_many :ratings
  has_one :user_stat
  after_create :make_platform_user

  def make_platform_user
    Platform.all.ids.each do |platform_id|
      PlatformUser.create(platform_id: platform_id, user_id: self.id)
    end
  end

  def set_stat
    user_stat = self.user_stat
    if user_stat.nil?
      user_stat = UserStat.new
      user_stat.user_id = self.id
    end

    stat = Array.new
    total = Array.new

    0.upto(4).each do |i|
      stat[i] = 0
      total[i] = 0
    end
    ratings = self.ratings
    ratings.each do |rating|
      game_stat = rating.game.game_stat
      0.upto(4).each do |i|
        stat[i] += game_stat.send("stat#{i}") * rating.score
        total[i] += rating.score
      end
    end

    user_stat.stat0 = stat[0].to_f/total[0]
    user_stat.stat1 = stat[1].to_f/total[1]
    user_stat.stat2 = stat[2].to_f/total[2]
    user_stat.stat3 = stat[3].to_f/total[3]
    user_stat.stat4 = stat[4].to_f/total[4]
    user_stat.save
  end

  def get_order_by_sd games
    arr = Array.new
    user_stat = self.user_stat
    game_stats = Array.new
    genre_rating = Array.new

    self.ratings.each do |rating|
      rating.game.genre_ids.split("/").each do |genre_id|
        if genre_rating[genre_id.to_i].nil?
          genre_rating[genre_id.to_i] = 0
        end
        genre_rating[genre_id.to_i] += rating.score
      end
    end

    games.each do |game|
      game_stats.push(game.game_stat)
      game.genre_ids.split("/")
    end

    total_sd = 0
    total_gs = 0

    game_stats.each do |game_stat|
      var = 0
      0.upto(4) do |i|
        var += (game_stat.send("stat#{i}") - user_stat.send("stat#{i}")) ** 2
      end
      sd = var ** 0.5
      total_sd += sd
      game = game_stat.game
      genre_score = 0
      game.genre_ids.split("/").each do |genre_id|
        unless genre_rating[genre_id.to_i].nil?
          genre_score += genre_rating[genre_id.to_i]
        end
      end
      total_gs += genre_score;
      total_sd += sd;

      arr.push({game:game,
                sd:sd,
                gs:genre_score
      })
    end
    arr.each do |a|
      a[:ratio_sd] = a[:sd] * (total_gs/total_sd)
      a[:ret] =  a[:ratio_sd] + a[:gs]
    end

    arr.sort_by!{|x| x[:ret]}
    arr.reverse!

    stand = arr[0][:ret].to_f
    arr.each do |a|
      a[:ret] = (a[:ret].to_f / stand * 5.0)
      a[:ret] ='%.1f' %  a[:ret]
    end

    arr
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :image, :genre_id, :device_ids)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for @game, :html => { :multipart => true } do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= file_field_tag "game[image]" %>
  </div>
  <div class="field">
    <%= f.label :genre_ids %><br>
    <%= f.text_field :genre_ids %>
  </div>
  <div class="field">
    <%= f.label :platform_ids %><br>
    <%= f.text_field :platform_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Genre ids</th>
      <th>Platform ids</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.image %></td>
        <td><%= game.genre_id %></td>
        <td><%= game.platform_ids %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%=@game.image.url(:midium)%>" alt="" />
</p>

<p>
  <strong>Genre:</strong>
  <%= @game.genre_ids %>
</p>

<p>
  <strong>platform ids:</strong>
  <%= @game.platform_ids %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>