config/routes.rb
GameWatcha::Application.routes.draw do
  resources :game_infos

  post "api/signin"
  post "api/signup"
  post "api/game_info"
  post "api/make_comment"
  post "api/set_rating"
  post "api/wish"
  get "page/index"
  get "picbox" => "page#my_wish"
  post "/api/delete_comment"
  root "page#index"
  post "/api/set_user_platform"
  get "main" => "page#main"
  get "detail" => "page#detail"
  get "select" => "page#select"
  devise_for :users
  resources :games

end

app/models/game_info.rb
class GameInfo < ActiveRecord::Base
  has_attached_file :image, :styles => { :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :game
  def get_data
    game_info = self.attributes
    game_info["genre_name"] = self.game.genre_names
    game_info["platform_name"] = self.game.platform_names
    game_info["image_url"] = self.image.url(:original)
    game_info
  end
end

app/controllers/game_infos_controller.rb
class GameInfosController < ApplicationController
  before_action :set_game_info, only: [:show, :edit, :update, :destroy]

  # GET /game_infos
  # GET /game_infos.json
  def index
    @game_infos = GameInfo.all
  end

  # GET /game_infos/1
  # GET /game_infos/1.json
  def show
  end

  # GET /game_infos/new
  def new
    @game_info = GameInfo.new
  end

  # GET /game_infos/1/edit
  def edit
  end

  # POST /game_infos
  # POST /game_infos.json
  def create
    @game_info = GameInfo.new(game_info_params)

    respond_to do |format|
      if @game_info.save
        format.html { redirect_to @game_info, notice: 'Game info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @game_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_infos/1
  # PATCH/PUT /game_infos/1.json
  def update
    respond_to do |format|
      if @game_info.update(game_info_params)
        format.html { redirect_to @game_info, notice: 'Game info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_infos/1
  # DELETE /game_infos/1.json
  def destroy
    @game_info.destroy
    respond_to do |format|
      format.html { redirect_to game_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_info
      @game_info = GameInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_info_params
      params.require(:game_info).permit(:game_id, :maker, :distribute, :date, :class, :movie, :content)
    end
end

app/helpers/game_infos_helper.rb
module GameInfosHelper
end

app/views/game_infos/_form.html.erb
<%= form_for(@game_info) do |f| %>
  <% if @game_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_info.errors.count, "error") %> prohibited this game_info from being saved:</h2>

      <ul>
      <% @game_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :maker %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :distribute %><br>
    <%= f.text_field :distribute %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.text_field :class %>
  </div>
  <div class="field">
    <%= f.label :movie %><br>
    <%= f.text_field :movie %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_infos/edit.html.erb
<h1>Editing game_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_info %> |
<%= link_to 'Back', game_infos_path %>

app/views/game_infos/index.html.erb
<h1>Listing game_infos</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Maker</th>
      <th>Distribute</th>
      <th>Date</th>
      <th>Class</th>
      <th>Movie</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_infos.each do |game_info| %>
      <tr>
        <td><%= game_info.game_id %></td>
        <td><%= game_info.maker %></td>
        <td><%= game_info.distribute %></td>
        <td><%= game_info.date %></td>
        <td><%= game_info.class %></td>
        <td><%= game_info.movie %></td>
        <td><%= game_info.content %></td>
        <td><%= link_to 'Show', game_info %></td>
        <td><%= link_to 'Edit', edit_game_info_path(game_info) %></td>
        <td><%= link_to 'Destroy', game_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game info', new_game_info_path %>

app/views/game_infos/new.html.erb
<h1>New game_info</h1>

<%= render 'form' %>

<%= link_to 'Back', game_infos_path %>

app/views/game_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_info.game_id %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @game_info.maker %>
</p>

<p>
  <strong>Distribute:</strong>
  <%= @game_info.distribute %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game_info.date %>
</p>

<p>
  <strong>Class:</strong>
  <%= @game_info.class %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @game_info.movie %>
</p>

<p>
  <strong>Content:</strong>
  <%= @game_info.content %>
</p>

<%= link_to 'Edit', edit_game_info_path(@game_info) %> |
<%= link_to 'Back', game_infos_path %>